services:
  haproxy:
    image: haproxy:2.8.14
    volumes:
    - ".:/usr/local/etc/haproxy/:ro"
    ports:
    - "127.0.0.1:8080:80"
    - "127.0.0.1:8443:443"
    - "127.0.0.1:9080:8080"
    - "127.0.0.1:9000:9000"
    deploy:
      mode: global
